# -*- coding: utf-8 -*-
"""Convert a mysqldump (MySQL 8) export to a PostgreSQL-importable SQL file.

Design decisions:
- tinyint(1) -> boolean  (Laravel boolean columns created as tinyint(1) on MySQL)
- tinyint(unsigned)     -> smallint
- int unsigned          -> bigint (values like unix epoch fit in integer but be safe)
- enum/set              -> varchar(255)
- json                  -> json
- datetime/timestamp    -> timestamp (without time zone)
- auto-increment PK     -> bigint GENERATED BY DEFAULT AS IDENTITY
- sequences initialized from each table's AUTO_INCREMENT value
- data INSERTs emit explicit column lists, MySQL escape sequences unescaped,
  then re-escaped for PostgreSQL standard_conforming_strings=on literals
- foreign keys kept; data load runs with session_replication_role=replica
"""
import re
import sys
import os

SRC = os.environ.get('MYSQL_DUMP_PATH') or (
    sys.argv[1] if len(sys.argv) > 1 else r'C:\Users\66107\Desktop\workorder-system-8-10\storage\workorder_prod_export.sql')
DST = os.environ.get('PGSQL_OUT_PATH') or (
    sys.argv[2] if len(sys.argv) > 2 else r'C:\Users\66107\AppData\Local\Temp\opencode\workorder_postgres.sql')

def mysql_unescape(s: str) -> str:
    out = []
    i = 0
    n = len(s)
    while i < n:
        c = s[i]
        if c == '\\' and i + 1 < n:
            nx = s[i + 1]
            mp = {'n': '\n', 'r': '\r', 't': '\t', 'b': '\b', '0': '\0',
                  'Z': '\x1a', '\\': '\\', "'": "'", '"': '"', '%': '%', '_': '_'}
            out.append(mp.get(nx, nx))
            i += 2
        else:
            out.append(c)
            i += 1
    return ''.join(out)


def pg_escape(s: str) -> str:
    # standard_conforming_strings=on: only ' needs doubling. NUL bytes are invalid in PG.
    return s.replace("'", "''").replace('\x00', '')


class Converter:
    def __init__(self):
        self.out_lines = []
        self.tables = []          # ordered list of table dicts
        self.index_defs = []      # (table, index_name, cols) non-unique indexes
        self.seq_init = []        # (table, auto_increment_value)
        self.data_lines = []      # INSERT statements collected during scan
        self.fk_defs = []         # (table, constraint_sql) to add after data load

    def emit(self, s=''):
        self.out_lines.append(s)

    # ---------- schema ----------
    def convert_type(self, coltype: str, is_auto: bool) -> tuple:
        """Return (pg_type, is_boolean)."""
        t = coltype.strip()
        unsigned = 'unsigned' in t
        t = re.sub(r'\bunsigned\b', '', t).strip()
        m = re.match(r'^([a-z]+)(\([^)]*\))?', t)
        base = (m.group(1) or '').lower()
        args = m.group(2) or ''

        if base in ('bigint',):
            return 'bigint', False
        if base in ('int', 'integer'):
            return ('bigint' if unsigned else 'integer'), False
        if base == 'mediumint':
            return 'integer', False
        if base == 'smallint':
            return 'smallint', False
        if base == 'tinyint':
            if args == '(1)':
                return 'boolean', True
            return 'smallint', False
        if base in ('decimal', 'numeric'):
            return 'numeric' + args, False
        if base == 'float':
            return 'double precision', False
        if base == 'double':
            return 'double precision', False
        if base in ('varchar', 'char'):
            return base + args, False
        if base in ('text', 'tinytext', 'mediumtext', 'longtext'):
            return 'text', False
        if base == 'json':
            return 'json', False
        if base in ('datetime', 'timestamp'):
            return 'timestamp', False
        if base == 'date':
            return 'date', False
        if base == 'time':
            return 'time', False
        if base in ('enum', 'set'):
            return 'varchar(255)', False
        if base in ('blob', 'mediumblob', 'longblob', 'binary', 'varbinary'):
            return 'bytea', False
        if base == 'bit':
            return 'smallint', False
        # fallback
        return base + args, False

    def convert_default(self, default: str, is_boolean: bool):
        """default is the text after DEFAULT, e.g. '0'  NULL  CURRENT_TIMESTAMP."""
        v = default.strip()
        if v.upper() in ('NULL',):
            return 'DEFAULT NULL'
        if v.upper() in ('CURRENT_TIMESTAMP', 'CURRENT_TIMESTAMP()'):
            return 'DEFAULT CURRENT_TIMESTAMP'
        if is_boolean:
            if v.startswith("'") and v.endswith("'"):
                b = v[1:-1]
                return 'DEFAULT TRUE' if b not in ('0', 'false', '') else 'DEFAULT FALSE'
            if v in ('0', '1'):
                return 'DEFAULT TRUE' if v == '1' else 'DEFAULT FALSE'
            return 'DEFAULT ' + v
        if v.startswith("'") and v.endswith("'"):
            return "DEFAULT '" + pg_escape(mysql_unescape(v[1:-1])) + "'"
        if v.startswith("b'") and v.endswith("'"):
            bits = v[2:-1]
            return 'DEFAULT ' + str(int(bits, 2)) if bits else 'DEFAULT 0'
        if v.startswith('0x'):
            try:
                return 'DEFAULT ' + str(int(v[2:], 16))
            except ValueError:
                return None
        return 'DEFAULT ' + v

    def parse_create_table(self, stmt: str):
        m = re.match(r'CREATE TABLE `([^`]+)` \((.*)\)\s*(ENGINE[^;]*)?;', stmt, re.S)
        if not m:
            raise RuntimeError('Cannot parse CREATE TABLE:\n' + stmt[:300])
        name = m.group(1)
        body = m.group(2)
        engine_clause = m.group(3) or ''
        auto_match = re.search(r'AUTO_INCREMENT=(\d+)', engine_clause)

        columns = []
        constraints = []
        fk_defs = []
        for line in body.split('\n'):
            ln = line.strip().rstrip(',')
            if not ln:
                continue
            cm = re.match(r'^`([^`]+)`\s+(.+)$', ln)
            if cm:
                colname = cm.group(1)
                rest = cm.group(2)
                auto = 'AUTO_INCREMENT' in rest
                not_null = 'NOT NULL' in rest
                dflt = None
                dm = re.search(r'DEFAULT\s+(.*?)(?:\s+COMMENT\b|\s+ON UPDATE\b|$)', rest, re.S)
                if dm:
                    dflt = dm.group(1).strip()
                coltype_text = rest
                for kw in ('AUTO_INCREMENT', 'NOT NULL', 'DEFAULT', 'COMMENT', 'ON UPDATE', 'COLLATE'):
                    coltype_text = re.split(r'\b' + kw + r'\b', coltype_text)[0]
                coltype_text = coltype_text.replace('unsigned', '').strip()
                pg_type, is_bool = self.convert_type(coltype_text, auto)
                parts = [colname, pg_type]
                if auto:
                    parts.append('GENERATED BY DEFAULT AS IDENTITY')
                if not_null and not auto:
                    parts.append('NOT NULL')
                if dflt is not None and not auto:
                    c = self.convert_default(dflt, is_bool)
                    if c:
                        parts.append(c)
                columns.append({'name': colname, 'pg_type': pg_type, 'is_bool': is_bool,
                                'parts': parts})
                continue
            # table-level: PRIMARY KEY / UNIQUE KEY / KEY / CONSTRAINT
            if ln.startswith('PRIMARY KEY'):
                cols = ','.join(re.findall(r'`([^`]+)`', ln))
                constraints.append('PRIMARY KEY (' + cols + ')')
            elif ln.startswith('UNIQUE KEY'):
                um = re.match(r'UNIQUE KEY `([^`]+)`\s*\((.*)\)', ln)
                nm = um.group(1)
                cols = ','.join(re.findall(r'`([^`]+)`', um.group(2)))
                constraints.append('CONSTRAINT ' + nm + ' UNIQUE (' + cols + ')')
            elif ln.startswith('KEY '):
                km = re.match(r'KEY `([^`]+)`\s*\((.*)\)', ln)
                nm = km.group(1)
                cols = ','.join(re.findall(r'`([^`]+)`', km.group(2)))
                self.index_defs.append((name, nm, cols))
            elif ln.startswith('CONSTRAINT'):
                # CONSTRAINT `name` FOREIGN KEY (`a`) REFERENCES `t` (`b`) ON DELETE CASCADE
                nm = re.search(r'CONSTRAINT `([^`]+)`', ln).group(1)
                fk = re.search(r'FOREIGN KEY \(`([^`]+)`\) REFERENCES `([^`]+)` \(`([^`]+)`\)', ln)
                if fk:
                    fk_line = ('CONSTRAINT ' + nm + ' FOREIGN KEY (' + fk.group(1) +
                               ') REFERENCES ' + fk.group(2) + ' (' + fk.group(3) + ')')
                    ondel = re.search(r'ON DELETE ([\w ]+?)(?: ON UPDATE|$) *$', ln)
                    if ondel:
                        fk_line += ' ON DELETE ' + ondel.group(1).strip()
                    fk_line += ' NOT VALID'
                    fk_defs.append((name, fk_line))
                else:
                    raise RuntimeError('Unhandled CONSTRAINT in ' + name + ': ' + ln)
            else:
                raise RuntimeError('Unhandled table line in ' + name + ': ' + ln)

        if not columns:
            raise RuntimeError('No columns parsed for ' + name)

        self.tables.append({
            'name': name,
            'columns': columns,
            'constraints': constraints,
            'auto_increment': int(auto_match.group(1)) if auto_match else None,
        })
        if fk_defs:
            self.fk_defs.extend(fk_defs)

    def ddl(self):
        self.emit('-- PostgreSQL schema converted from MySQL dump')
        self.emit('BEGIN;')
        for t in self.tables:
            self.emit('DROP TABLE IF EXISTS %s CASCADE;' % t['name'])
        self.emit('')
        for t in self.tables:
            lines = ['CREATE TABLE %s (' % t['name']]
            col_lines = [('  ' + ' '.join(c['parts'])) + (',' if i < len(t['columns']) - 1 or t['constraints'] else '')
                         for i, c in enumerate(t['columns'])]
            if t['constraints']:
                col_lines[-1] = '  ' + ' '.join(t['columns'][-1]['parts']) + ','
            body_lines = list(col_lines)
            for i, cc in enumerate(t['constraints']):
                body_lines.append('  ' + cc + (',' if i < len(t['constraints']) - 1 else ''))
            lines.extend(body_lines)
            lines.append(');')
            self.emit('\n'.join(lines))
            self.emit('')
            if t['auto_increment']:
                self.seq_init.append((t['name'], t['auto_increment']))
        self.emit('SET session_replication_role = replica;')

    # ---------- data ----------
    @staticmethod
    def split_rows(values_text: str):
        rows = []
        i = 0
        n = len(values_text)
        while i < n:
            while i < n and values_text[i] not in '(':
                i += 1
            if i >= n:
                break
            j = i + 1
            depth = 1
            while j < n and depth > 0:
                c = values_text[j]
                if c == "'":
                    j += 1
                    while j < n:
                        if values_text[j] == '\\':
                            j += 2
                            continue
                        if values_text[j] == "'":
                            if j + 1 < n and values_text[j + 1] == "'":
                                j += 2
                                continue
                            j += 1
                            break
                        j += 1
                    continue
                if c == '(':
                    depth += 1
                elif c == ')':
                    depth -= 1
                j += 1
            rows.append(values_text[i + 1:j - 1])
            i = j
        return rows

    @staticmethod
    def split_fields(row: str):
        fields = []
        i = 0
        n = len(row)
        depth = 0
        cur = []
        while i < n:
            c = row[i]
            if c == "'":
                j = i + 1
                while j < n:
                    if row[j] == '\\':
                        j += 2
                        continue
                    if row[j] == "'":
                        if j + 1 < n and row[j + 1] == "'":
                            j += 2
                            continue
                        j += 1
                        break
                    j += 1
                cur.append(row[i:j])
                i = j
                continue
            if c == '(':
                depth += 1
            elif c == ')':
                depth -= 1
            if c == ',' and depth == 0:
                fields.append(''.join(cur).strip())
                cur = []
                i += 1
                continue
            cur.append(c)
            i += 1
        if cur or fields:
            fields.append(''.join(cur).strip())
        return fields

    def convert_value(self, field: str, is_bool: bool):
        if field == 'NULL':
            return 'NULL'
        if field.startswith("'") and field.endswith("'") and len(field) >= 2:
            s = mysql_unescape(field[1:-1])
            if is_bool:
                return 'TRUE' if s not in ('0', 'false', '') else 'FALSE'
            return "'" + pg_escape(s) + "'"
        if field.startswith('0x'):
            return "'\\x" + field[2:] + "'::bytea"
        if field.startswith("b'") and field.endswith("'"):
            bits = field[2:-1]
            return str(int(bits, 2)) if bits else '0'
        if is_bool:
            try:
                return 'TRUE' if int(field) != 0 else 'FALSE'
            except ValueError:
                return field
        return field

    def data_insert(self, table_name: str, values_text: str):
        t = next((x for x in self.tables if x['name'] == table_name), None)
        if not t:
            raise RuntimeError('INSERT for unknown table ' + table_name)
        cols = [c['name'] for c in t['columns']]
        bools = {c['name']: c['is_bool'] for c in t['columns']}
        rows = self.split_rows(values_text)
        out_rows = []
        for row in rows:
            fields = self.split_fields(row)
            if len(fields) != len(cols):
                raise RuntimeError('Column count mismatch for %s: got %d expected %d\n%s' %
                                   (table_name, len(fields), len(cols), row[:400]))
            converted = [self.convert_value(f, bools[c]) for f, c in zip(fields, cols)]
            out_rows.append('(' + ','.join(converted) + ')')
        self.data_lines.append('INSERT INTO %s (%s) VALUES\n%s;' % (
            table_name, ','.join(cols), ',\n'.join(out_rows)))

    def finish(self):
        self.emit('SET session_replication_role = default;')
        self.emit('')
        if self.fk_defs:
            self.emit('-- foreign keys')
            for table, fk in self.fk_defs:
                self.emit('ALTER TABLE %s ADD %s;' % (table, fk))
            self.emit('')
        self.emit('-- reset identity sequences to match MySQL AUTO_INCREMENT values')
        for table, ai in self.seq_init:
            self.emit("SELECT setval(pg_get_serial_sequence('%s','id'), %d, false);" % (table, ai))
        self.emit('')
        self.emit('-- secondary indexes')
        seen = {}
        for table, idx, cols in self.index_defs:
            if idx in seen:
                raise RuntimeError('Duplicate index name %s (tables %s and %s)' % (idx, seen[idx], table))
            seen[idx] = table
            self.emit('CREATE INDEX %s ON %s (%s);' % (idx, table, cols))
        self.emit('COMMIT;')

    def run(self):
        text = open(SRC, encoding='utf-8').read()
        lines = text.split('\n')
        i = 0
        n = len(lines)
        while i < n:
            line = lines[i].strip()
            if not line or line.startswith('--') or line.startswith('/*'):
                i += 1
                continue
            if line.startswith('DROP TABLE'):
                i += 1
                continue
            if line.startswith('LOCK TABLES') or line.startswith('UNLOCK TABLES'):
                i += 1
                continue
            if line.startswith('/*!40000 ALTER TABLE'):
                i += 1
                continue
            if line.startswith('INSERT INTO'):
                m = re.match(r'INSERT INTO `([^`]+)` VALUES (.*);$', line)
                if not m:
                    raise RuntimeError('Cannot parse INSERT line: ' + line[:200])
                self.data_insert(m.group(1), m.group(2))
                i += 1
                continue
            if line.startswith('CREATE TABLE'):
                buf = [line]
                while i < n and not buf[-1].rstrip().endswith(';'):
                    i += 1
                    buf.append(lines[i])
                stmt = '\n'.join(buf)
                self.parse_create_table(stmt)
                i += 1
                continue
            # ignore other statements (SET, version comments already skipped)
            i += 1

        self.ddl()
        for ln in self.data_lines:
            self.emit(ln)
        self.finish()
        out = '\n'.join(self.out_lines)
        with open(DST, 'w', encoding='utf-8', newline='\n') as f:
            f.write(out)
        print('Wrote', DST, len(out), 'bytes', len(self.tables), 'tables')


if __name__ == '__main__':
    Converter().run()
